# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-17 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extractions', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects.Project', verbose_name='projects'),
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together=set([('aliquot', 'ext_id', 'analyte')]),
        ),
        migrations.AlterIndexTogether(
            name='extraction',
            index_together=set([('aliquot', 'ext_id', 'analyte')]),
        ),
    ]
