# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-20 21:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0002_auto_20151117_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='ext_id',
            field=models.CharField(default='UNKNOWN', help_text='The sequencing center id.', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='sequencing center id'),
        ),
        migrations.AlterUniqueTogether(
            name='extraction',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='extraction',
            index_together=set([]),
        ),
    ]
