# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-27 21:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0003_auto_20151125_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='ext_id',
            field=models.CharField(default='UNKNOWN', help_text='The sequencing center ID.', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='sequencing center ID'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='int_id',
            field=models.CharField(max_length=100, null=True, verbose_name='internal ID'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='platform',
            field=models.CharField(choices=[('UNKNOWN', 'UNKNOWN'), ('HISEQ', 'HISEQ'), ('ILLUMINA-XTEN', 'ILLUMINA-XTEN'), ('AGILENT-50MB', 'AGILENT-50MB'), ('AGILENT-51MB', 'AGILENT-51MB'), ('PAIRED-END-50BP', 'PAIRED-END-50BP'), ('SINGLE-END-150BP', 'SINGLE-END-150BP'), ('HEMEPACT-V1', 'HEMEPACT-V1'), ('HEMEPACT-V2', 'HEMEPACT-V2'), ('HEMEPACT-V3', 'HEMEPACT-V3'), ('IMPACT-HEME', 'IMPACT-HEME'), ('IMPACT-300', 'IMPACT-300'), ('IMPACT-340', 'IMPACT-340'), ('IMPACT-CLINICAL', 'IMPACT-CLINICAL'), ('H3K4ME1', 'H3K4ME1'), ('H3K4ME3', 'H3K4ME3'), ('H3K4ME2', 'H3K4ME2'), ('H3K27AC', 'H3K27AC'), ('FOUNDATIONONE-HEME-PANEL', 'FOUNDATIONONE-HEME-PANEL'), ('FOUNDATIONONE-PANEL', 'FOUNDATIONONE-PANEL')], default='UNKNOWN', max_length=100, null=True, verbose_name='platform'),
        ),
    ]
