# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-02 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0009_auto_20151202_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='workflows_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, null=True, verbose_name='number of extractions created'),
        ),
    ]
