# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-09 20:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0012_auto_20151209_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='aliquot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aliquots.Aliquot', verbose_name='aliquot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extraction',
            name='ext_id',
            field=models.CharField(blank=True, default='UNKNOWN', help_text='The sequencing center ID.', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='sequencing center ID'),
        ),
    ]
