# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-21 21:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0013_auto_20151209_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='ext_id',
            field=models.CharField(blank=True, default='UNKNOWN', help_text='The sequencing center ID.', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_./\\s]+\\Z')], verbose_name='sequencing center ID'),
        ),
    ]
