# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-23 17:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('individuals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, choices=[('Blood', 'Blood'), ('Nails', 'Nails'), ('Buccal', 'Buccal'), ('Hair', 'Hair'), ('T-Cells', 'T-Cells')], max_length=100, null=True, verbose_name='source')),
                ('source_type', models.CharField(choices=[('TUMOR', 'Tumor'), ('NORMAL', 'Normal')], max_length=100, null=True, verbose_name='source_type')),
                ('ext_id', models.CharField(help_text='The external id should be unique at the Individual and Source levels.', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='external id')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='desired order')),
                ('aliquots_count', models.PositiveSmallIntegerField(default=0, editable=False, null=True, verbose_name='number of aliquots created')),
                ('int_id', models.CharField(editable=False, max_length=8, null=True, verbose_name='internal id')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='slug')),
                ('individual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='individuals.Individual', verbose_name='individual')),
            ],
            options={
                'verbose_name_plural': 'specimens',
                'verbose_name': 'specimen',
            },
        ),
        migrations.AlterUniqueTogether(
            name='specimen',
            unique_together=set([('individual', 'ext_id', 'source_type')]),
        ),
        migrations.AlterIndexTogether(
            name='specimen',
            index_together=set([('individual', 'ext_id', 'source_type')]),
        ),
    ]
