# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-30 20:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0002_auto_20151125_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='ext_id',
            field=models.CharField(default='UNKNOWN', help_text='The external id should be unique at the Individual and Source type levels.', max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='external id'),
        ),
    ]
