# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0004_auto_20151209_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='source_type',
            field=models.CharField(choices=[('TUMOR', 'TUMOR'), ('NORMAL', 'NORMAL'), ('QUERY', 'QUERY')], max_length=100, null=True, verbose_name='source_type'),
        ),
    ]
