# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-23 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import leukapp.apps.leukforms.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leukform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='This is for your future self.', max_length=140, null=True, verbose_name='description')),
                ('submission', models.FileField(null=True, upload_to='leukform/submissions/%Y/%m', validators=[leukapp.apps.leukforms.validators.leukform_csv_validator], verbose_name='leukform')),
                ('result', models.FileField(blank=True, null=True, upload_to='leukform/results/%Y/%m', verbose_name='sumbission result')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='summary')),
                ('mock', models.NullBooleanField(default=False, help_text='if True, records will not be saved.', verbose_name='test leukform')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name_plural': 'leukforms',
                'verbose_name': 'leukform',
            },
        ),
    ]
