# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='read_length',
            field=models.CharField(choices=[('50', '50'), ('100', '100'), ('125', '125'), ('150', '150'), ('200', '200'), ('225', '225'), ('250', '250')], max_length=100, null=True, verbose_name='read length'),
        ),
    ]
