# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-03 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_auto_20151203_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='sequencing_center',
            field=models.CharField(choices=[('CMO', 'CMO'), ('NYGC', 'NYGC'), ('FOUNDATION', 'FOUNDATION'), ('ILLUMINA', 'ILLUMINA'), ('SANGER', 'SANGER')], max_length=100, null=True, verbose_name='sequencing center'),
        ),
    ]
