# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-12 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import leukapp.apps.workflows.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20151210_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='projects_string',
            field=models.CharField(blank=True, help_text="Include the projects keys separated by a '|' character", max_length=100, null=True, validators=[leukapp.apps.workflows.validators.projects_string_validator], verbose_name='list of projetcs'),
        ),
    ]
