# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-03 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import leukapp.apps.core.db


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeukappTestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('testme', leukapp.apps.core.db.CharNullField(blank=True, default='UNKNOWN', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
