# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-03 20:46
from __future__ import unicode_literals

from django.db import migrations
import leukapp.apps.core.db


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leukapptestmodel',
            name='testme',
            field=leukapp.apps.core.db.CharNullField(blank=True, default='UNKNOWN', max_length=100, null=True),
        ),
    ]
