# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-09 20:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0004_auto_20151203_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='ext_id',
            field=models.CharField(default='', help_text='The external id should be unique at the Institution and Species levels. MRNs are not allowed for Individuals coming from MSK. Please use a pseudo MRN or other type of identifier.', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='external id'),
            preserve_default=False,
        ),
    ]
