# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-17 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individuals', '0005_auto_20151209_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='queries_count',
            field=models.PositiveSmallIntegerField(default=0, editable=False, null=True, verbose_name='number of query specimens created'),
        ),
    ]
