# -*- coding: utf-8 -*-

"""
Models/database schemas for the :mod:`~leukapp.apps.individuals` application.

See `Django's Model Documentation`_ for more information.

.. _Django's Model Documentation:
    https://docs.djangoproject.com/en/1.9/topics/db/models/
"""

# django
from django.db import models
from django.utils.translation import ugettext_lazy as _

# leukapp
from leukapp.apps.core.models import LeukappModel
from leukapp.apps.core.validators import ext_id_validator

# local
from . import constants


class Individual(LeukappModel):

    """
    Top model in the **Leukgen's** samples ecosystem.

    This class usually refers to patients, mice and other kind of organisms
    described in the :data:`.constants.SPECIES`.
    """

    #: Name of the application where :class:`Individual` is contained.
    APP_NAME = constants.APP_NAME

    # EXTERNAL FIELDS
    # =========================================================================

    ext_id = models.CharField(
        verbose_name=_("external id"),
        validators=[ext_id_validator],
        max_length=100,
        help_text=_(
            "The external id should be unique at the Institution and Species "
            "levels. MRNs are not allowed for Individuals coming from MSK. "
            "Please use a pseudo MRN or other type of identifier."
            ),
        )
    """
    Id used by the scientist or Institution to track the :class:`Individual`.
    This field is validated using the
    :obj:`~leukapp.apps.core.validators.ext_id_validator`.

    .. warning::
        **MRNs** are not allowed for **HUMANS** from **MSK**. Please enforce
        the use a pseudo MRN or other type of identifier.
    """

    institution = models.CharField(
        verbose_name=_("institution"),
        choices=constants.INDIVIDUAL_CHOICES["INSTITUTION"],
        max_length=100,
        null=True,
        )
    """
    Indicates whether the :class:`Individual` comes from MSK or not.
    The two available choices in :data:`~constants.INSTITUTION` are ``MSK``
    and ``OTHER``.
    """

    species = models.CharField(
        verbose_name=_("species"),
        choices=constants.INDIVIDUAL_CHOICES["SPECIES"],
        max_length=100,
        null=True,
        )
    """
    Indicates the :class:`Individual` species. See the available choices:
    :data:`~constants.SPECIES`.
    """

    # INTERNAL FIELDS
    # =========================================================================
    tumors_count = models.PositiveSmallIntegerField(
        verbose_name=_("number of tumor specimens created"),
        default=0,
        editable=False,
        null=True,
        )
    """
    Count of TUMOR specimens linked with the :class:`Individual`. See the
    :class:`~leukapp.apps.specimens.models.Specimen` class for more
    information.
    """

    normals_count = models.PositiveSmallIntegerField(
        verbose_name=_("number of normal specimens created"),
        default=0,
        editable=False,
        null=True,
        )
    """
    Count of NORMAL specimens linked with the :class:`Individual`. See the
    :class:`~leukapp.apps.specimens.models.Specimen` class for more
    information.
    """

    queries_count = models.PositiveSmallIntegerField(
        verbose_name=_("number of query specimens created"),
        default=0,
        editable=False,
        null=True,
        )
    """
    Count of QUERY specimens linked with the :class:`Individual`.A query
    Specimen is a sample that is collected from non-tumor locations, but is
    likely to have mutations.

    See the :class:`~leukapp.apps.specimens.models.Specimen` class for more
    information.
    """

    int_id = models.CharField(
        verbose_name=_("internal id"),
        max_length=100,
        editable=False,
        null=True,
        )
    """
    Internal ID used to describe the :class:`Individual` instance.

    This value is generated by :meth:`_get_int_id` and includes the positions
    ``[1-3]`` of the **leukid** (e.g. ``E-H-100000``):

    1.  ``E`` indicates that the current instance comes from an **external**
        institution. If ``I``, comes from MSK.
    2.  ``100000`` indicates the primary key in the mod:`leukapp` system.
    3.  ``H`` indicates the species of the :class:`Individual` following the
        character assignment described in :data:`~.constants.INT_ID_SPECIES`

    .. important::
        The :attr:`int_id` is generated only once. If there was a mistake a new
        :class:`Individual` instance must be created.
    """

    slug = models.SlugField(
        verbose_name=_("slug"),
        unique=True,
        editable=False,
        null=True,
        )
    """
    :class:`Individual's <.Individual>` unique identifier (**leukid**).

    .. important::
        For the :class:`Individual` model, the :attr:`int_id` and :attr:`slug`
        are the same. However, this does not apply for the children classes
        :class:`~leukapp.apps.specimens.models.Specimen`,
        :class:`~leukapp.apps.aliquots.models.Aliquot`, and
        :class:`~leukapp.apps.extractions.models.Extraction`.
    """

    # META CLASS
    # =========================================================================
    class Meta:
        verbose_name = _(constants.APP_NAME[:-1])
        verbose_name_plural = _(constants.APP_NAME)
        unique_together = (constants.INDIVIDUAL_UNIQUE_TOGETHER)
        index_together = (constants.INDIVIDUAL_UNIQUE_TOGETHER)

    # PUBLIC METHODS
    # =========================================================================
    def __str__(self):
        """Return slug when str is called on object."""
        return self.slug

    def check_institution(self):
        """Determine whether or not the :class:`Individual` comes from MSK."""
        if self.institution == constants.MSK:
            return 'I'
        else:
            return 'E'

    # PRIVATE METHODS
    # =========================================================================
    def _if_new(self, **kwargs):
        """
        Executed only when the object is created.

        .. currentmodule::
            leukapp.apps.core
        .. note::
            This method can only be called from
            :meth:`~models.LeukappModel.save` and is protected by
            :meth:`~models.LeukappModel._check_if_caller_is_save`.
        """
        self._check_if_caller_is_save()
        self._get_int_id()
        self.slug = self.int_id

    def _if_save(self):
        """
        Executed everytime the object is saved.

        .. currentmodule::
            leukapp.apps.core
        .. note::
            This method can only be called from
            :meth:`~models.LeukappModel.save` and is protected by
            :meth:`~models.LeukappModel._check_if_caller_is_save`.
        """
        self._check_if_caller_is_save()

    def _get_int_id(self):
        """
        Compute the :attr:`int_id`.

        Steps:

            * Check if the caller function is :meth:`_if_new()`.
            * Retrieve the ID character assigned to the ``species`` field.

        .. note::
            This method can only be called from
            :meth:`_if_new` and is protected by
            :meth:`~leukapp.apps.core.models.LeukappModel._check_if_caller_is_if_new`.
        """
        self._check_if_caller_is_if_new()

        species_id = constants.INT_ID_SPECIES[self.species]
        institution_id = self.check_institution()
        to_join = [institution_id, species_id, str(self.pk)]
        self.int_id = "-".join(to_join)
        return self.int_id
