#!/bin/bash

# LEUKAPP SPECIFIC ENVIRONMENT VARIABLES
# -----------------------------------------------------------------------------
export LEUKDC_ROOT_DIR=/ifs/work/leukgen/leukapp/$DEPLOYMENT
export LEUKDC_BACKUPDB_DIR=$LEUKDC_ROOT_DIR/db
export LEUKDC_PROJECTS_DIR=$LEUKDC_ROOT_DIR/projects
export LEUKDC_SAMPLES_DIR=$LEUKDC_ROOT_DIR/samples
export LEUKDC_HOST="luna.mskcc.org"
export LEUKDC_USER="medinaj"
export LEUKDC_PASSWORD=""
export LEUKDC_SSHKEY=$HOME"/.ssh/id_rsa.pub"
export LEUKDC_ACTIVE="TRUE"
