#!/bin/bash

# LOCAL CONFIGURATION
# =============================================================================
export DEPLOYMENT="local"
export DJANGO_SETTINGS_MODULE="config.settings.local"
export PROJECT_DIR=/Users/medinaj/projects/msk/leukapp

# LOAD LEUKAPP SPECIFIC ENVIRONMENT VARIABLES
# =============================================================================
. $PROJECT_DIR/.env/leukapp

# GO TO PROJECT DIRECTORY
# =============================================================================
cd $PROJECT_DIR
