#!/bin/bash
# This hook is run after this virtualenv is activated.

# PRODUCTION CONFIGURATION
# -----------------------------------------------------------------------------
export DEPLOYMENT="production"
export DJANGO_HOST=leukgen.mskcc.org

# PRODUCTION EMAIL CONFIGURATION
# -----------------------------------------------------------------------------
export DJANGO_DEFAULT_FROM_EMAIL="leukapp <noreply@leukgen.mskcc.org>"
export DJANGO_EMAIL_SUBJECT_PREFIX="[leukapp] "

# LOAD COMMON ENVIRONMENT VARIABLES
# -----------------------------------------------------------------------------
. . $PROJECT_DIR/.env/common

# LOAD LEUKAPP SPECIFIC ENVIRONMENT VARIABLES
# -----------------------------------------------------------------------------
. ./leukapp
