#!/bin/bash
# This is an example

export DJANGO_SETTINGS_MODULE=config.settings.production
export DJANGO_ALLOWED_HOSTS=leukgen.mskcc.org
export DATABASE_URL=postgres:///production
export DJANGO_SECRET_KEY=

cd /home/medinaj/sites/plvleukweb1.mskcc.org/source/

