#!/bin/bash
# This hook is run after this virtualenv is activated.

# django
export DJANGO_HOST=leukgen.mskcc.org
export DEPLOYMENT="production"
export DJANGO_SETTINGS_MODULE="config.settings.production"
export DJANGO_ALLOWED_HOSTS=$DJANGO_HOST
export DATABASE_URL=postgres:///$DEPLOYMENT
export DJANGO_SECRET_KEY=CHANGE_ME

# leukapp
export LEUKDC_PROJECTS_DIR="/ifs/res/papaemme/leukgen/"$DEPLOYMENT"/projects"
export LEUKDC_SAMPLES_DIR="/ifs/res/papaemme/leukgen/"$DEPLOYMENT"/samples/"
export LEUKDC_HOST="luna.mskcc.org"
export LEUKDC_USER="medinaj"
export LEUKDC_PASSWORD=""
export LEUKDC_SSHKEY=$HOME"/.ssh/id_rsa.pub"
export LEUKDC_ACTIVE="TRUE"

# leukapp directory
cd /home/medinaj/sites/$DJANGO_HOST/source/
