#!/bin/bash
# This is an example

export DJANGO_SETTINGS_MODULE=config.settings.staging
export DJANGO_ALLOWED_HOSTS=plvleukweb1.mskcc.org
export DATABASE_URL=postgres:///staging
export DJANGO_SECRET_KEY=CHANGE_ME

cd /home/medinaj/sites/plvleukweb1.mskcc.org/source/

