#!/bin/bash
# This hook is run after this virtualenv is activated.

# django
export DEPLOYMENT="staging"
export DJANGO_ALLOWED_HOSTS=plvleukweb1.mskcc.org
export DATABASE_URL=postgres:///staging
export DJANGO_SECRET_KEY=CHANGE_ME
export DJANGO_SETTINGS_MODULE="config.settings."$DEPLOYMENT

# leukapp
export LEUKDC_PROJECTS_DIR="/ifs/res/papaemme/leukgen/"$DEPLOYMENT"/projects"
export LEUKDC_HOST="luna.mskcc.org"
export LEUKDC_USER="medinaj"
export LEUKDC_PASSWORD=""
export LEUKDC_SSHKEY=$HOME"/.ssh/id_rsa.pub"

# leukapp directory
cd /home/medinaj/sites/plvleukweb1.mskcc.org/source/
