# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-17 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specimens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliquot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ext_id', models.CharField(help_text='The external id should be unique at the Specimen level.', max_length=100, validators=[django.core.validators.RegexValidator(code='invalid', message="Enter a valid 'External id' consisting of letters, numbers, underscores or hyphens.", regex='^[-a-zA-Z0-9_.]+\\Z')], verbose_name='external id')),
                ('int_id', models.CharField(editable=False, max_length=100, null=True, verbose_name='internal id')),
                ('dna_extractions_count', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='number of extractions created')),
                ('rna_extractions_count', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='number of extractions created')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='slug')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimens.Specimen', verbose_name='specimen')),
            ],
            options={
                'verbose_name': 'aliquot',
                'verbose_name_plural': 'aliquots',
            },
        ),
        migrations.AlterUniqueTogether(
            name='aliquot',
            unique_together=set([('specimen', 'ext_id')]),
        ),
        migrations.AlterIndexTogether(
            name='aliquot',
            index_together=set([('specimen', 'ext_id')]),
        ),
    ]
