# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-23 17:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('participants', '0002_participant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='projects_as_participant', to='participants.Participant', verbose_name='participants'),
        ),
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(help_text='Laboratory head or principal investigator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_pi', to='participants.Participant', verbose_name='principal investigator'),
        ),
        migrations.AddField(
            model_name='project',
            name='requestor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_as_requestor', to='participants.Participant', verbose_name='requestor'),
        ),
    ]
