# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-12-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20151123_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='protocol_no',
            field=models.CharField(max_length=100, null=True, verbose_name='IRB protocol number'),
        ),
    ]
